### ISSUE TITLE
Summarize in other languages

### ISSUE THREAD

**Issue by moshpirit** [avelino/logseq-summarize#4]
I'm Spanish, and would like to summarize in Spanish. IDK how, but it does that already for *some* websites, but not others (like [this one](https://feminicidio.net/la-revuelta-de-las-putas/)). It would be cool to add the language in the prompt when asking for the summary.

Also, it would be cool to be able to get more lines for big articles too.

**Comment by avelino** [comment]
this feature must be implemented in the prompt sent to LLM

does @ecarrara make sense for tldr.chat?

**Comment by ecarrara** [comment]
@moshpirit I added Spanish to the list of prompts used in tldr.chat. 

Could you please check if it's ok now?
https://tldr.chat/url/https://feminicidio.net/la-revuelta-de-las-putas/

System prompt: "Escribes resúmenes de texto cuando el usuario lo solicita para un texto extenso. Su resultado debe tener un párrafo que resuma el texto y, opcionalmente, una lista de viñetas."
User prompt: "Escriba un resumen conciso del siguiente texto delimitado por triples comillas.

**Comment by moshpirit** [comment]
> @moshpirit I added Spanish to the list of prompts used in tldr.chat.
> 
> Could you please check if it's ok now? https://tldr.chat/url/https://feminicidio.net/la-revuelta-de-las-putas/

It is cool, thanks! Although I would call "VIÑETAS" "CLAVES", since a "viñeta" is mainly a vignette, we don't use this word for bullet points; a better word could be "clave", which is a key point ("claves" in plural).

> System prompt: "Resume el texto cuando el usuario lo solicite para un texto extenso. Su resultado debe tener un párrafo que resuma el texto y, opcionalmente, una lista de claves."

FTFY

>User prompt: "Escriba un resumen conciso del siguiente texto delimitado por triples comillas.

Why triple quotation marks? Also, I think I need more context in order to translate this correctly: Where is this text visible? Is this a sentence that it is supposed to say the user? If so, I would change "Escriba" for "Escribe". 

Thanks for replying!

**Comment by avelino** [comment]
by closing this issue, we were able to fix the problem, apparently @ecarrara made updates on the tldr.chat side correcting what was reported
